### PR TITLE
feat(action): add support for custom npm registry

### LINKED ISSUE #38: Feature Request: To support custom npm registry as input
Feature Request: To support custom npm registry as input and use `npm` registry by default. In the future it could read `package.json` and/or `.npmrc`.

### PR DESCRIPTION
**Pull request by oscard0m**
Fix #38

---

Not tested, just drafted an initial proposal

### CODE REVIEW

**Review by gr2m — COMMENTED** [review]
looks good to me! Can you add documentation for the new input in the README and add the input to `action.yml`? If the change works for you we can merge it in. You can test your fork by doing

```yml
- uses oscard0m/await-npm-package-version-action
```

**Comment by oscard0m** [comment]
Trying to play with an unexisting package in GitHub Registry and `timeout` but seems like `timeout` is not cutting the execution on time:

https://github.com/oscard0m/sandbox/actions/runs/809394454
https://github.com/oscard0m/sandbox/actions/runs/809399611

Any clue on what could be the issue?

**Comment by gr2m** [comment]
> seems like `timeout` is not cutting the execution

Hmm it should end it, I'll have a look

**Comment by gr2m** [comment]
shoud be fixed now, can you try again?

**Comment by oscard0m** [comment]
I'm still getting a never ending GitHub Action execution: https://github.com/oscard0m/sandbox/runs/2504376343?check_suite_focus=true. Do you want me to create a follow up issue for this?

---

[Changed with GitHub Package](https://github.com/oscard0m/sandbox/runs/2504435137?check_suite_focus=true) I own and now I get a 404 (some authentication issues) but I guess the registry feature is working as expected.

**Comment by gr2m** [comment]
> Do you want me to create a follow up issue for this?

Yes please

> the `custom registry` feature is working as expected. Should we merge this part?

Yes, let's go

**Comment by gr2m** [comment]
@oscard0m I got an error that I think was introduced by your change, could you have a look:
https://github.com/octokit/openapi/runs/2512603282?check_suite_focus=true#step:2:41

image


I think the fix might be as simple as changing

```js
const getRegistryURL = (registry, package) => {
  const sanitizedPackageName = package.replace(/\//, "%2f");
  const registryURL = new URL(sanitizedPackageName, registry);

  return registryURL.toString();
}
```

to

```js
function getRegistryURL(registry, package) {
  const sanitizedPackageName = package.replace(/\//, "%2f");
  const registryURL = new URL(sanitizedPackageName, registry);

  return registryURL.toString();
}
```

because function declarations are hoisted, but const declarations are not

**Comment by oscard0m** [comment]
> @oscard0m I got an error that I think was introduced by your change, could you have a look:
> 
> https://github.com/octokit/openapi/runs/2512603282?check_suite_focus=true#step:2:41
> 
> 
> 
> image
> 
> 
> 
> 
> 
> I think the fix might be as simple as changing
> 
> 
> 
> ```js
> 
> const getRegistryURL = (registry, package) => {
> 
>   const sanitizedPackageName = package.replace(/\//, "%2f");
> 
>   const registryURL = new URL(sanitizedPackageName, registry);
> 
> 
> 
>   return registryURL.toString();
> 
> }
> 
> ```
> 
> 
> 
> to
> 
> 
> 
> ```js
> 
> function getRegistryURL(registry, package) {
> 
>   const sanitizedPackageName = package.replace(/\//, "%2f");
> 
>   const registryURL = new URL(sanitizedPackageName, registry);
> 
> 
> 
>   return registryURL.toString();
> 
> }
> 
> ```
> 
> 
> 
> because function declarations are hoisted, but const declarations are not

I take it.

Can it wait a few minutes until semifinal of UEFA Champions League finishes? 😜

**Comment by oscard0m** [comment]
> @oscard0m I got an error that I think was introduced by your change, could you have a look:
> 
> https://github.com/octokit/openapi/runs/2512603282?check_suite_focus=true#step:2:41
> 
> 
> 
> image
> 
> 
> 
> 
> 
> I think the fix might be as simple as changing
> 
> 
> 
> ```js
> 
> const getRegistryURL = (registry, package) => {
> 
>   const sanitizedPackageName = package.replace(/\//, "%2f");
> 
>   const registryURL = new URL(sanitizedPackageName, registry);
> 
> 
> 
>   return registryURL.toString();
> 
> }
> 
> ```
> 
> 
> 
> to
> 
> 
> 
> ```js
> 
> function getRegistryURL(registry, package) {
> 
>   const sanitizedPackageName = package.replace(/\//, "%2f");
> 
>   const registryURL = new URL(sanitizedPackageName, registry);
> 
> 
> 
>   return registryURL.toString();
> 
> }
> 
> ```
> 
> 
> 
> because function declarations are hoisted, but const declarations are not

I take it.

Can it wait a few minutes until semifinal of UEFA Champions League finishes? 😜

**Pull request merged**
